<a href="https://colab.research.google.com/github/jobayed80/Machine_Learning_Learning_Course/blob/main/Import_pandas_CSV_File_Read.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('shanghaiData.csv')
#if the file slxs, then
# df = pd.read_excel('file-name.xlsx')

In [11]:
df

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
...,...,...,...,...,...,...,...,...,...,...,...
4892,401-500,University of Trieste,11-20,NaN,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,NaN,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,NaN,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,NaN,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,NaN,0.0,0.0,14.9,7.5,25.0,11.9,2015

In [12]:
df.shape

(4897, 11)

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
# head() function that means first 5(default) rows show.
df.head()

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005

In [16]:
# tail() this function used for last five(default) rows show
df.tail()

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
4892,401-500,University of Trieste,11-20,NaN,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,NaN,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,NaN,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,NaN,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,NaN,0.0,0.0,14.9,7.5,25.0,11.9,2015

In [17]:
# head(10) that means first ten rows show
df.head(10)

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005
5,6,California Institute of Technology,5,67.1,59.2,68.6,59.8,65.8,52.5,100.0,2005
6,7,Columbia University,6,62.3,79.4,60.6,56.1,54.2,69.5,45.4,2005
7,8,Princeton University,7,60.9,63.4,76.8,60.9,48.7,48.5,59.1,2005
8,9,University of Chicago,8,60.1,75.6,81.9,50.3,44.7,56.4,42.2,2005
9,10,University of Oxford,2,59.7,64.3,59.1,48.4,55.6,68.4,53.2,2005

In [18]:
# tail(10) that means last ten rows show
df.tail(10)

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
4887,401-500,"University of Science, Malaysia",2,NaN,0.0,0.0,7.1,3.3,30.6,15.7,2015
4888,401-500,University of Seville,9-13,NaN,0.0,0.0,0.0,7.5,33.7,11.3,2015
4889,401-500,University of Surrey,34-37,NaN,0.0,0.0,8.6,4.9,27.0,18.0,2015
4890,401-500,University of Szeged,1-2,NaN,0.0,13.3,3.6,3.4,21.8,12.8,2015
4891,401-500,University of the Basque Country,9-13,NaN,0.0,0.0,3.6,7.1,36.1,13.5,2015
4892,401-500,University of Trieste,11-20,NaN,0.0,0.0,5.0,10.9,25.1,20.1,2015
4893,401-500,University of Zaragoza,9-13,NaN,0.0,0.0,7.6,5.1,33.3,13.1,2015
4894,401-500,Utah State University,126-146,NaN,13.6,0.0,3.6,10.8,25.1,15.5,2015
4895,401-500,Vienna University of Technology,4-6,NaN,0.0,0.0,0.0,12.2,28.8,22.9,2015
4896,401-500,Wake Forest University,126-146,NaN,0.0,0.0,14.9,7.5,25.0,11.9,2015